### ISSUE TITLE
syntax highlighting system

### ISSUE THREAD

**Issue by felixangell** [felixangell/phi-editor#21]
a simple syntax highlighting system proposal. languages are configured as such:

```toml
[file_associations]
c_language = [".c", ".h", ".cc"]

[syntax.c_language]
[syntax.c_language.type]
colouring = 0xff0000
match = [
	"int", "char", "bool", "float", "double", "void",
	"uint8_t", "uint16_t", "uint32_t", "uint64_t",
	"int8_t", "int16_t", "int32_t", "int64_t",
]

[syntax.c_language.keyword]
colouring = 0xff00ff
match = [
	"for", "break", "if", "else", "continue", "return",
	"goto", "static", "extern", "const", "typedef",
]
```

the gist is. we register the file association i.e. c_language is associated with the given file extensions.

then we define the syntax highlighting for the language as `syntax.language_name`. a syntax specifies types of values as well as their colouring, and what they can match.

obviously this is not very flexible but for basic syntax highlighting its quite good and easy to customize. in the future perhaps you can specify regex or something to match identifiers in different ways e.g. what regex pattern is a number `f([0-9]+)` would match `f323` or something like that
